PIP=pip3
PYTHON=python3

.PHONY: setup help clean train test

run: setup convert

setup: requirements.txt
	$(PIP) install -r requirements.txt

help:
	@echo "This is a help string."

clean:
	@echo "Cleaning temporary masks."

convert:
	$(PYTHON) -m rationai.data.tiler.xml_annot_patcher --config_fp $(CONFIG_FILE)
