PIP=pip3
PYTHON=python3

.PHONY: setup help clean train test

run: setup convert

setup: requirements.txt
	$(PIP) install -r requirements.txt

help:
	@echo "This is a help string."

clean:
	@echo "Cleaning temporary masks."

convert:
	@mkdir -p "$(OUTPUT_DIR)"
	$(PYTHON) -m rationai.data.slide_converter --config_fp $(CONFIG_FILE) --output_dir $(OUTPUT_DIR)
